[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
SliceMap = "82cb661a-3f19-5665-9e27-df437c7e54c8"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
