[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SliceMap = "82cb661a-3f19-5665-9e27-df437c7e54c8"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
