name = "FluxArchitectures"
uuid = "53d20848-f986-4c56-957e-0e417ec068db"
authors = ["S. Dobbersch√ºtz <sdobberschuetz@gmx.net> and contributors"]
version = "0.2.5"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BSON = "0.3"
Flux = "0.13"
LazyArtifacts = "1"
Reexport = "1"
Revise = "3"
Tables = "1"
Zygote = "<0.6.44"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
