name = "FluxArchitectures"
uuid = "53d20848-f986-4c56-957e-0e417ec068db"
authors = ["Sören Dobberschütz <sdobberschuetz@gmx.net> and contributors"]
version = "0.1.1"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SliceMap = "82cb661a-3f19-5665-9e27-df437c7e54c8"

[compat]
BSON = "0.3"
Flux = "0.12"
JuliennedArrays = "0.2"
LazyArtifacts = "1"
Reexport = "1"
Revise = "3"
SliceMap = "0.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
